import { getStroke } from 'perfect-freehand';

/**
 * Converts a flat array of points [x1, y1, x2, y2, ...] 
 * into an array of coordinate pairs [[x1, y1], [x2, y2], ...]
 */
export function formatFlatPoints(points) {
  if (!points || !points.length) return [];
  const formatted = [];
  for (let i = 0; i < points.length; i += 2) {
    formatted.push([points[i], points[i + 1]]);
  }
  return formatted;
}

/**
 * Converts the outline points generated by perfect-freehand into an SVG path string.
 */
export function getSvgPathFromStroke(stroke) {
  if (!stroke || !stroke.length) return "";

  const d = stroke.reduce(
    (acc, [x0, y0], i, arr) => {
      const [x1, y1] = arr[(i + 1) % arr.length];
      acc.push(x0, y0, (x0 + x1) / 2, (y0 + y1) / 2);
      return acc;
    },
    ["M", ...stroke[0], "Q"]
  );

  d.push("Z");
  return d.join(" ");
}

/**
 * Generates the SVG Path string directly from flat points
 */
export function getFreehandPath(points, size = 16, isMarker = false) {
  const formattedPoints = formatFlatPoints(points);
  
  if (formattedPoints.length === 0) return "";
  
  // Use slightly different settings for marker vs pen
  const stroke = getStroke(formattedPoints, {
    size: size,
    thinning: isMarker ? 0 : 0.5,
    smoothing: 0.5,
    streamline: 0.5,
    easing: (t) => t,
    start: {
      taper: isMarker ? 0 : size,
      easing: (t) => t,
      cap: true
    },
    end: {
      taper: isMarker ? 0 : size,
      easing: (t) => t,
      cap: true
    }
  });

  return getSvgPathFromStroke(stroke);
}
